"""
CVSS Guru — Database migration runner (PostgreSQL).

Usage:
    python scripts/migrate.py            # apply all pending migrations
    python scripts/migrate.py --status   # show which migrations are applied

How it works:
  1. Creates a `schema_migrations` table on first run (idempotent).
  2. Compares the list of known migrations against the applied ones.
  3. Applies the pending ones in order, each inside a single transaction
     (PostgreSQL DDL is transactional, so a failed migration leaves no trace).
  4. A transaction-level advisory lock makes concurrent runs safe: when several
     gunicorn workers start at once, only one applies the migrations.

Adding a new migration:
  - Append a (version, description, [sql, ...]) entry to MIGRATIONS.
  - Use the next zero-padded version: "002", "003", ...
  - Never edit or delete an entry that has been applied somewhere.

The `citext` extension must exist in the database; it is created by the
database administrator together with the database (it needs superuser rights).
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from dotenv import load_dotenv

load_dotenv()

import psycopg
from psycopg.rows import dict_row

# Arbitrary constant identifying the CVSS Guru migration lock
_LOCK_ID = 7_310_402_025

_CREATE_MIGRATIONS_TABLE = """
CREATE TABLE IF NOT EXISTS schema_migrations (
    version     TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

# ── Migration registry ────────────────────────────────────────────────────────

MIGRATIONS: list[tuple[str, str, list[str]]] = [
    (
        "001",
        "Initial schema: users, api_usage, password_reset_tokens, ai_scorer_queries",
        [
            """
            CREATE TABLE users (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username    CITEXT      NOT NULL UNIQUE,
                email       CITEXT      NOT NULL UNIQUE,
                password    TEXT        NOT NULL,
                api_key     TEXT        UNIQUE,
                created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
                last_login  TIMESTAMPTZ
            )
            """,
            """
            CREATE TABLE api_usage (
                user_id     BIGINT  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                year_month  TEXT    NOT NULL CHECK (year_month ~ '^[0-9]{4}-[0-9]{2}$'),
                call_count  INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (user_id, year_month)
            )
            """,
            """
            CREATE TABLE password_reset_tokens (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                token       TEXT        NOT NULL UNIQUE,
                expires_at  TIMESTAMPTZ NOT NULL,
                used        BOOLEAN     NOT NULL DEFAULT FALSE,
                created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """,
            "CREATE INDEX password_reset_tokens_user_id_idx ON password_reset_tokens (user_id)",
            """
            CREATE TABLE ai_scorer_queries (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id     BIGINT      REFERENCES users (id) ON DELETE CASCADE,
                description TEXT        NOT NULL,
                result_json JSONB,
                created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """,
            "CREATE INDEX ai_scorer_queries_user_id_idx ON ai_scorer_queries (user_id)",
        ],
    ),
    (
        "002",
        "Store API keys as SHA-256 hashes; shared rate-limit table",
        [
            # Existing keys keep working: the hash of the same key is computed here.
            "ALTER TABLE users ADD COLUMN api_key_hash TEXT UNIQUE",
            "ALTER TABLE users ADD COLUMN api_key_prefix TEXT",
            """
            UPDATE users
               SET api_key_hash = encode(sha256(convert_to(api_key, 'UTF8')), 'hex'),
                   api_key_prefix = left(api_key, 8)
             WHERE api_key IS NOT NULL
            """,
            # Plaintext keys are wiped now; the column itself is dropped in a later
            # migration so the previous release keeps working during a rolling deploy.
            "UPDATE users SET api_key = NULL",
            """
            CREATE TABLE rate_limit_hits (
                bucket  TEXT        NOT NULL,
                key     TEXT        NOT NULL,
                hit_at  TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """,
            "CREATE INDEX rate_limit_hits_lookup_idx ON rate_limit_hits (bucket, key, hit_at)",
        ],
    ),
    (
        "003",
        "Drop the old plaintext api_key column (emptied by 002)",
        [
            "ALTER TABLE users DROP COLUMN IF EXISTS api_key",
        ],
    ),
    (
        "004",
        "Email verification: users.email_verified_at + verification tokens",
        [
            "ALTER TABLE users ADD COLUMN email_verified_at TIMESTAMPTZ",
            # Accounts created before verification existed are not locked out.
            "UPDATE users SET email_verified_at = created_at",
            """
            CREATE TABLE email_verification_tokens (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                token_hash  TEXT        NOT NULL UNIQUE,
                expires_at  TIMESTAMPTZ NOT NULL,
                created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """,
            "CREATE INDEX email_verification_tokens_user_id_idx ON email_verification_tokens (user_id)",
        ],
    ),
]

# ── Runner ────────────────────────────────────────────────────────────────────


def run_migrations(verbose: bool = True) -> int:
    """Apply all pending migrations. Returns the number applied.

    Raises RuntimeError if DATABASE_URL is not configured.
    """
    dsn = os.getenv("DATABASE_URL", "")
    if not dsn:
        raise RuntimeError("DATABASE_URL is not set in environment variables.")

    applied_now = 0
    # A short-lived synchronous connection: migrations run once at startup,
    # independently of the application's async pool.
    with psycopg.connect(dsn, row_factory=dict_row, connect_timeout=5) as conn:
        with conn.transaction():
            conn.execute("SELECT pg_advisory_xact_lock(%s)", [_LOCK_ID])
            conn.execute(_CREATE_MIGRATIONS_TABLE)
            done = {r["version"] for r in conn.execute("SELECT version FROM schema_migrations")}

            for version, description, statements in MIGRATIONS:
                if version in done:
                    continue
                if verbose:
                    print(f"  Applying {version}: {description} ...")
                with conn.transaction():  # savepoint: one migration = all or nothing
                    for sql in statements:
                        conn.execute(sql)
                    conn.execute(
                        "INSERT INTO schema_migrations (version, description) VALUES (%s, %s)",
                        [version, description],
                    )
                applied_now += 1

    if verbose:
        print(f"{applied_now} migration(s) applied." if applied_now else "Database is up to date.")
    return applied_now


def print_status() -> None:
    """Print the current migration status."""
    with psycopg.connect(os.environ["DATABASE_URL"], row_factory=dict_row) as conn:
        rows = {r["version"]: r["applied_at"] for r in conn.execute(
            "SELECT version, applied_at FROM schema_migrations ORDER BY version"
        )}
    print(f"\n{'Version':<10} {'Status':<24} Description")
    print("-" * 72)
    for version, description, _ in MIGRATIONS:
        status = f"applied {rows[version]:%Y-%m-%d %H:%M}" if version in rows else "pending"
        print(f"{version:<10} {status:<24} {description}")
    print()


if __name__ == "__main__":
    if "--status" in sys.argv:
        print_status()
    else:
        print("Running database migrations...\n")
        run_migrations(verbose=True)
