/**
 * Copy the third-party front-end assets from node_modules into app/static/vendor/
 * so the site serves everything itself (no Google Fonts / unpkg / cdnjs at runtime:
 * better privacy under GDPR, fewer points of failure, simpler CSP).
 *
 * Usage:  npm install && npm run vendor
 * The generated files are committed; re-run after changing a version in package.json.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const NM = path.join(ROOT, "node_modules");
const OUT = path.join(ROOT, "app", "static", "vendor");

function copy(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
  console.log("  " + path.relative(ROOT, to));
}

fs.rmSync(OUT, { recursive: true, force: true });

// ── HTMX and highlight.js ─────────────────────────────────────────────────────
copy(path.join(NM, "htmx.org/dist/htmx.min.js"), path.join(OUT, "htmx.min.js"));
copy(path.join(NM, "@highlightjs/cdn-assets/highlight.min.js"), path.join(OUT, "highlight/highlight.min.js"));
copy(path.join(NM, "@highlightjs/cdn-assets/styles/atom-one-dark.min.css"), path.join(OUT, "highlight/atom-one-dark.min.css"));

// ── Swagger UI for /docs (FastAPI's default loads it from a CDN, blocked by our CSP) ──
copy(path.join(NM, "swagger-ui-dist/swagger-ui-bundle.js"), path.join(OUT, "swagger/swagger-ui-bundle.js"));
copy(path.join(NM, "swagger-ui-dist/swagger-ui.css"), path.join(OUT, "swagger/swagger-ui.css"));

// ── Phosphor icons (regular + fill): CSS + woff2/woff only ────────────────────
for (const [dir, font] of [["regular", "Phosphor"], ["fill", "Phosphor-Fill"]]) {
  const src = path.join(NM, "@phosphor-icons/web/src", dir);
  for (const ext of ["woff2", "woff"]) copy(path.join(src, `${font}.${ext}`), path.join(OUT, "phosphor", dir, `${font}.${ext}`));
  // Keep only the formats we ship in the @font-face src list
  const css = fs.readFileSync(path.join(src, "style.css"), "utf8").replace(
    /src:\s*url\([^;]*;/,
    `src: url("./${font}.woff2") format("woff2"), url("./${font}.woff") format("woff");`
  );
  fs.writeFileSync(path.join(OUT, "phosphor", dir, "style.css"), css);
  console.log("  " + path.relative(ROOT, path.join(OUT, "phosphor", dir, "style.css")));
}

// ── Fonts: Inter (variable, 100–900) and Cormorant Garamond 600 italic ────────
// Only Latin + Latin Extended subsets (the site is in English).
const SUBSETS = ["latin", "latin-ext"];
const faces = [];
function fontFaces(cssFile, family, filesDir, outPrefix) {
  const css = fs.readFileSync(cssFile, "utf8");
  for (const block of css.match(/\/\*[^*]*\*\/\s*@font-face\s*{[^}]*}/g) || []) {
    const subset = (block.match(/\/\*\s*[\w-]+-([\w-]+?)-(?:wght|\d+)-/) || [])[1];
    const url = (block.match(/url\(\.\/files\/([^)]+\.woff2)\)/) || [])[1];
    if (!url || !SUBSETS.some((s) => url.includes(`-${s}-`))) continue;
    copy(path.join(filesDir, url), path.join(OUT, "fonts", url));
    faces.push(
      block
        .replace(/\/\*[^*]*\*\/\s*/, `/* ${outPrefix} ${url.includes("-latin-ext-") ? "latin-ext" : "latin"} */\n`)
        .replace(/font-family:\s*'[^']+'/, `font-family: '${family}'`)
        .replace(/src:[^;]*;/, `src: url(./${url}) format('woff2');`)
    );
  }
}
fontFaces(path.join(NM, "@fontsource-variable/inter/wght.css"), "Inter",
  path.join(NM, "@fontsource-variable/inter/files"), "Inter");
fontFaces(path.join(NM, "@fontsource/cormorant-garamond/600-italic.css"), "Cormorant Garamond",
  path.join(NM, "@fontsource/cormorant-garamond/files"), "Cormorant Garamond 600 italic");

fs.writeFileSync(
  path.join(OUT, "fonts", "fonts.css"),
  "/* Self-hosted fonts (generated by scripts/vendor_assets.js, SIL Open Font License) */\n" + faces.join("\n") + "\n"
);
console.log("  " + path.relative(ROOT, path.join(OUT, "fonts", "fonts.css")) + ` (${faces.length} faces)`);
